Easy2GetRoom/Models/FilterViewModel.cs
using Easy2GetRoom.Application.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Easy2GetRoom.Models
{
    public class FilterViewModel
    {
        public List<PropertyCategoryViewModel> PropertyCategories { get; set; }

        public List<RentalTypeViewModel> RentalTypes { get; set; }

        public List<CityViewModel> ListCities { get; set; }

        public List<DistrictViewModel> ListDistricts { get; set; }

        public List<WardsViewModel> ListWards { get; set; }
    }
}

Easy2GetRoom/Models/NewsViewModels/DetailViewModel.cs
using Easy2GetRoom.Application.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Easy2GetRoom.Models.NewsViewModels
{
    public class DetailViewModel
    {
        public List<NewsViewModel> LastestNews { get; set; }

        public NewsViewModel News { get; set; }
    }
}

Easy2GetRoom/Models/PropertyViewModels/CatalogViewModel.cs
using Easy2GetRoom.Application.ViewModels;
using Easy2GetRoom.Utilities.Dtos;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Easy2GetRoom.Models.PropertyViewModels
{
    public class CatalogViewModel
    {
        public PagedResult<PropertyViewModel> Data { get; set; }

        public PropertyCategoryViewModel Category { get; set; }

        public string SortType { get; set; }

        public int? PageSize { get; set; }

        public List<SelectListItem> SortTypes { get; } = new List<SelectListItem>
        {
            new SelectListItem() {Value = "lastest", Text = "Mới nhất"},
            new SelectListItem() {Value = "price", Text = "Giá"},
            new SelectListItem() {Value = "name", Text= "Tên"},
        };
    }
}

Easy2GetRoom/Models/PropertyViewModels/DetailViewModel.cs
using Easy2GetRoom.Application.ViewModels;
using System.Collections.Generic;

namespace Easy2GetRoom.Models.PropertyViewModels
{
    public class DetailViewModel
    {
        public PropertyViewModel Property { get; set; }

        public List<PropertyViewModel> RelatedProperties { get; set; }

        public PropertyCategoryViewModel Category { get; set; }

        public List<PropertyImageViewModel> PropertyImages { get; set; }
    }
}

Easy2GetRoom/Models/PropertyViewModels/FilterViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Easy2GetRoom.Models.PropertyViewModels
{
    public class FilterViewModel
    {
        public int? Category { get; set; }

        public int? RentalType { get; set; }

        public int? City { get; set; }

        public int? District { get; set; }

        public int? Wards { get; set; }

        public int? AcreageRange { get; set; }

        public int? PriceRange { get; set; }

        public int? Page { get; set; }

        public int? PageSize { get; set; }
    }
}

Easy2GetRoom/Areas/Admin/Controllers/PropertyController.cs
using Easy2GetRoom.Application.Interfaces;
using Easy2GetRoom.Application.ViewModels;
using Easy2GetRoom.Data.Enums;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System.Collections.Generic;
using System.Linq;

namespace Easy2GetRoom.Areas.Admin.Controllers
{
    public class PropertyController : BaseController
    {
        private IPropertyService _propertyService;
        private IPropertyCategoryService _propertyCategoryService;

        public PropertyController(IPropertyService propertyService, IPropertyCategoryService propertyCategoryService)
        {
            _propertyService = propertyService;
            _propertyCategoryService = propertyCategoryService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        #region AJAX API

        [HttpGet]
        public IActionResult GetAll()
        {
            var model = _propertyService.GetAll();
            return new OkObjectResult(model);
        }

        [HttpGet]
        public IActionResult GetAllCategories()
        {
            var model = _propertyCategoryService.GetAll();
            return new OkObjectResult(model);
        }

        [HttpGet]
        public IActionResult GetAllPaging(int? categoryId, string keyWord, int page, int pageSize)
        {
            var model = _propertyService.GetAllPaging(categoryId, keyWord, page, pageSize);
            return new OkObjectResult(model);
        }

        [HttpGet]
        public IActionResult GetById(int id)
        {
            var model = _propertyService.GetById(id);
            return new OkObjectResult(model);
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            _propertyService.Delete(id);
            _propertyService.Save();

            return new OkResult();
        }

        public IActionResult Update(int id, Status status)
        {
            PropertyViewModel property = _propertyService.GetById(id);
            property.Status = status;
            _propertyService.Update(property);
            _propertyService.Save();
            return new OkResult();
        }

        [HttpPost]
        public IActionResult SaveEntity(PropertyViewModel propertyViewModel)
        {
            if (!ModelState.IsValid)
            {
                IEnumerable<ModelError> allErrors = ModelState.Values.SelectMany(v => v.Errors);
                return new BadRequestObjectResult(allErrors);
            }
            else
            {
                if (propertyViewModel.Id == 0)
                {
                    //Add new property
                }
                else
                {
                    //Update property
                    _propertyService.Update(propertyViewModel);
                }
                _propertyService.Save();

                return new OkObjectResult(propertyViewModel);
            }
        }

        public IActionResult SetSlideFlag(int id, int isFlag)
        {
            _propertyService.UpdateSlideFlag(id, isFlag);
            _propertyService.Save();
            return new OkResult();
        }
        #endregion AJAX API
    }
}

Easy2GetRoom/Controllers/Components/PagerViewComponent.cs
using Easy2GetRoom.Utilities.Dtos;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Easy2GetRoom.Controllers.Components
{
    public class PagerViewComponent : ViewComponent
    {
        public Task<IViewComponentResult> InvokeAsync(PagedResultBase result)
        {
            return Task.FromResult((IViewComponentResult)View("Default", result));
        }
    }
}

Easy2GetRoom/Controllers/Components/SlideViewComponent.cs
using Easy2GetRoom.Application.Interfaces;
using Easy2GetRoom.Application.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Easy2GetRoom.Controllers.Components
{
    public class SlideViewComponent : ViewComponent
    {

        private IPropertyService _propertyService;

        public SlideViewComponent(IPropertyService propertyService)
        {
            _propertyService = propertyService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var properties = new List<PropertyViewModel>();
            properties = _propertyService.GetAllSlideProperty();
            return View(properties);
        }
    }
}

Easy2GetRoom/Controllers/PropertyController.cs
using Easy2GetRoom.Application.Interfaces;
using Easy2GetRoom.Models.PropertyViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

namespace Easy2GetRoom.Controllers
{
    public class PropertyController : Controller
    {
        private IPropertyService _propertyService;
        private IPropertyCategoryService _propertyCategoryService;
        private IPropertyImageService _propertyImageService;

        private IConfiguration _configuration;

        public PropertyController(IPropertyService propertyService, IPropertyCategoryService propertyCategoryService,
            IPropertyImageService propertyImageService, IConfiguration configuration)
        {
            _propertyService = propertyService;
            _propertyCategoryService = propertyCategoryService;
            _propertyImageService = propertyImageService;
            _configuration = configuration;
        }

        [Route("filter-result.html")]
        public IActionResult Filter(int? categoryId, int? rentalTypeId, int? cityId, int? districtId,
            int? wardsId, int? acreageRange, int? priceRange, int page = 1)
        {
            var catalog = new CatalogViewModel();

            var pageSize = _configuration.GetValue<int>("PageSize");
            catalog.PageSize = pageSize;
            catalog.Data = _propertyService.GetFilterPaging(categoryId, rentalTypeId, cityId, districtId, wardsId, acreageRange,
                priceRange, page, pageSize);
            return View(catalog);
        }

        [Route("search-result.html")]
        public IActionResult Search(string keyword, int? pageSize, string sortBy, int page = 1)
        {
            var catalog = new SearchResultViewModel();

            if (pageSize == null)
            {
                pageSize = _configuration.GetValue<int>("PageSize");
            }
            catalog.PageSize = pageSize;
            catalog.Data = _propertyService.GetAllActivePropertyPaging(null, keyword, page, pageSize.Value, null);
            catalog.Keyword = keyword;

            return View(catalog);
        }

        [Route("easy2getroom-property-c.{id}.html")]
        public IActionResult CataLog(int id, string keyword, int? pageSize, string sortBy, int page = 1)
        {
            var catalog = new CatalogViewModel();

            if (pageSize == null)
            {
                pageSize = _configuration.GetValue<int>("PageSize");
            }

            catalog.Data = _propertyService.GetAllActivePropertyPaging(id, string.Empty, page, pageSize.Value, null);

            return View(catalog);
        }

        [Route("all-properties.html")]
        public IActionResult AllProperties(string keyword, int? pageSize, string sortBy, int page = 1)
        {
            var catalog = new CatalogViewModel();

            if (pageSize == null)
            {
                pageSize = _configuration.GetValue<int>("PageSize");
            }

            catalog.Data = _propertyService.GetAllActivePropertyPaging(null, string.Empty, page, pageSize.Value, null);
            return View(catalog);
        }

        [Route("easy2getroom-property-p.{id}.html", Name = "PropertyDetail")]
        public IActionResult Details(int id)
        {
            var model = new DetailViewModel();
            model.Property = _propertyService.GetById(id);
            model.PropertyImages = _propertyImageService.GetPropertyImageByPropertyId(id);
            model.RelatedProperties = _propertyService.GetRelatedProperties(id, 3);
            return View(model);
        }
    }
}

Easy2GetRoom/Views/Property/AllProperties.cshtml
@using Easy2GetRoom.Models.PropertyViewModels
@model CatalogViewModel

@{
    ViewData["Title"] = "Danh sách bài đăng";
}
@(await Component.InvokeAsync("Slide"))
@(await Component.InvokeAsync("FilterProperty"))
<div class="site-section site-section-sm bg-light">
    <div class="container">
        <div class="row mb-5">
            <div class="col-12">
                <div class="site-section-title">
                    <h2>Các bài đăng mới cho bạn</h2>
                </div>
            </div>
        </div>
        <div class="row mb-5">
            @foreach (var item in Model.Data.Results)
            {
                var url = "/easy2getroom-property-p." + item.Id + ".html";
                <div class="col-md-6 col-lg-4 mb-4">
                    <a href="@url" class="prop-entry d-block">
                        <figure>
                            @if (item.PropertyImages.Count() != 0)
                            {
                                <img style="max-height:350px;
                                            width: 100%;"
                                     src="@item.PropertyImages[0].Url" alt="@item.Name" class="img-fluid">
                            }
                            else
                            {
                                <img src="~/client/images/img_1.jpg" alt="@item.Name" class="img-fluid">
                            }
                        </figure>
                        <div class="prop-text">
                            <div class="inner">
                                <span class="price rounded">@item.Price.ToString("N0") VNĐ</span>
                                <h3 class="title">@item.Title</h3>
                                <p class="location">@item.Address</p>
                            </div>
                            <div class="prop-more-info">
                                <div class="inner d-flex">
                                    <div class="col">
                                        <span>Diện tích:</span>
                                        <strong>@item.Acreage<sup>2</sup></strong>
                                    </div>
                                    <div class="col">
                                        <span>Loại:</span>
                                        <strong>@item.RentalType.Name</strong>
                                    </div>
                                    <div class="col">
                                        <span>Đăng bởi:</span>
                                        <strong>@item.User.FullName</strong>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            }
        </div>
        @(await Component.InvokeAsync("Pager", Model.Data))
    </div>
</div>

Easy2GetRoom/Views/Property/CataLog.cshtml
@using Easy2GetRoom.Models.PropertyViewModels
@model CatalogViewModel

@{
    ViewData["Title"] = "Danh sách bài đăng";
}
@(await Component.InvokeAsync("Slide"))
@(await Component.InvokeAsync("FilterProperty"))
<div class="site-section site-section-sm bg-light">
    <div class="container">
        <div class="row mb-5">
            <div class="col-12">
                <div class="site-section-title">
                    <h2>Các bài đăng mới cho bạn</h2>
                </div>
            </div>
        </div>
        <div class="row mb-5">
            @foreach (var item in Model.Data.Results)
            {
                var url = "/easy2getroom-property-p." + item.Id + ".html";
                <div class="col-md-6 col-lg-4 mb-4">
                    <a href="@url" class="prop-entry d-block">
                        <figure>
                            @if (item.PropertyImages.Count() != 0)
                            {
                                <img style="max-height:350px;
                                            width: 100%;"
                                     src="@item.PropertyImages[0].Url" alt="@item.Name" class="img-fluid">
                            }
                            else
                            {
                                <img src="~/client/images/img_1.jpg" alt="@item.Name" class="img-fluid">
                            }
                        </figure>
                        <div class="prop-text">
                            <div class="inner">
                                <span class="price rounded">@item.Price.ToString("N0") VNĐ</span>
                                <h3 class="title">@item.Title</h3>
                                <p class="location">@item.Address</p>
                            </div>
                            <div class="prop-more-info">
                                <div class="inner d-flex">
                                    <div class="col">
                                        <span>Diện tích:</span>
                                        <strong>@item.Acreage<sup>2</sup></strong>
                                    </div>
                                    <div class="col">
                                        <span>Loại:</span>
                                        <strong>@item.RentalType.Name</strong>
                                    </div>
                                    <div class="col">
                                        <span>Đăng bởi:</span>
                                        <strong>@item.User.FullName</strong>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            }
        </div>
        @(await Component.InvokeAsync("Pager", Model.Data));

    </div>
</div>

Easy2GetRoom/Views/Property/Details.cshtml
@using Easy2GetRoom.Models.PropertyViewModels

@model DetailViewModel

@{
    ViewData["Title"] = "Details";

    var category = Model.Property.PropertyCategory;
    var property = Model.Property;
    var propertyImages = Model.Property.PropertyImages;
    var relatedProperties = Model.RelatedProperties;

}

@section Styles {
    <link href="~/lib/ckeditor/skins/moono/editor.css" rel="stylesheet" />
}

@section Scripts {
    <script src="~/lib/ckeditor/ckeditor.js"></script>
    <script src="~/client/js/controllers/detail/index.js"></script>
    <script>
        var detail = new detailController();
        detail.initialize();
    </script>
    <script src="~/client/js/controllers/detail/initmap.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBEfLTmYpED4HyRSF1KaSyyqZ7m7ZGYxpU&callback=initMap">
    </script>
    <script>
        var map = new initMap();
        map.initialize();
    </script>

}
<div class="site-blocks-cover overlay" style="background-image: url(/uploaded/backgrounds/hochiminh-city.jpg);" data-aos="fade"
     data-stellar-background-ratio="0.5">
    <div class="container">
        <div class="row align-items-center justify-content-center text-center">
            <div class="col-md-10">
                <span class="d-inline-block text-white px-3 mb-3 property-offer-type rounded">Trang chi tiết</span>
                <h1 class="mb-2">@property.Title</h1>
            </div>
        </div>
    </div>
</div>

<div class="site-section site-section-sm">
    <div class="container">
        <div class="row">
            <div class="col-lg-8" style="margin-top: -150px;">
                <div class="mb-5">
                    <div class="slide-one-item home-slider owl-carousel">
                        @if (Model.PropertyImages.Count() != 0)
                        {
                            @foreach (var image in Model.PropertyImages)
                            {
                                <div><img style="max-height:730px;" src="@image.Url"></div>
                            }
                        }
                        else
                        {
                            <div><img style="max-height:730px;" src="~/client/images/img_1.jpg"></div>
                            <div><img style="max-height:730px;" src="~/client/images/img_2.jpg"></div>
                        }

                    </div>
                </div>
                <div class="bg-white">
                    <div class="row mb-5">
                        @if (property.Price == 0)
                        {
                            <div class="col-md-6">
                                <strong class="text-success h3 mb-3">@property.PriceFrom.ToString("N0") đến @property.PriceTo.ToString("N0") VNĐ</strong>
                            </div>
                        }
                        else
                        {
                            <div class="col-md-6">
                                <strong class="text-success h3 mb-3">@property.Price.ToString("N0") VNĐ</strong>
                            </div>
                        }
                    </div>
                    <div class="row mb-5">
                        <div class="col-md-6 col-lg-3 text-left border-bottom border-top py-3">
                            <span class="d-inline-block text-black mb-0 caption-text">Loại </span>
                            <strong class="d-block">@property.PropertyCategory.Name</strong>
                        </div>
                        <div class="col-md-6 col-lg-3 text-left border-bottom border-top py-3">
                            <span class="d-inline-block text-black mb-0 caption-text">Được đăng bởi</span>
                            <strong class="d-block">@property.User.FullName</strong>
                        </div>
                        <div class="col-md-6 col-lg-3 text-left border-bottom border-top py-3">
                            <span class="d-inline-block text-black mb-0 caption-text">Vào lúc</span>
                            <strong class="d-block">@property.DateCreated</strong>
                        </div>
                        <div class="col-md-6 col-lg-3 text-left border-bottom border-top py-3">
                            <span class="d-inline-block text-black mb-0 caption-text">Số điện thoại</span>
                            <strong class="d-block">@property.User.PhoneNumber.</strong>
                        </div>
                    </div>
                    <input id="txtLat" hidden value="@property.Lat" />
                    <input id="txtLng" hidden value="@property.Lng" />
                    <h2 class="h4 text-black">Mô tả chi tiết</h2>
                    <textarea id="txtDescriptionTemp" style="display:none;" hidden>@property.Description</textarea>
                    <p id="txtDescription">
                        @property.Description
                    </p>
                    <div class="row mt-5">
                        <div class="col-12">
                            <h2 class="h4 text-black mb-3">Hình ảnh chi tiết</h2>
                        </div>
                        @foreach (var image in Model.PropertyImages)
                        {
                            <div class="col-sm-6 col-md-4 col-lg-3 mb-4">
                                <a href="@image.Url" class="image-popup gal-item">
                                    <img src="@image.Url" alt="Image"
                                         class="img-fluid">
                                </a>
                            </div>
                        }
                    </div>
                </div>
            </div>
            <div class="col-lg-4 pl-md-2">

                <div class="bg-white widget border rounded">

                </div>
                <div class="form-group">
                    <h3>Vị trí</h3>
                </div>
                <div class="bg-white border rounded">
                    <div id="map" style="height:350px;"></div>
                </div>

            </div>

        </div>
    </div>
</div>

<div class="site-section site-section-sm bg-light">
    <div class="container">

        <div class="row">
            <div class="col-12">
                <div class="site-section-title mb-5">
                    <h2>Bài đăng liên quan</h2>
                </div>
            </div>
        </div>

        <div class="row mb-5">
            @foreach (var item in relatedProperties)
            {
                var url = "/easy2getroom-property-p." + item.Id + ".html";
                <div class="col-md-6 col-lg-4 mb-4">
                    <a href="@url" class="prop-entry d-block">
                        <figure>
                            @if (item.PropertyImages.Count() != 0)
                            {
                                <img style="max-height:350px;
                                            width: 100%;"
                                     src="@item.PropertyImages[0].Url" alt="@item.Name" class="img-fluid">
                            }
                            else
                            {
                                <img src="~/client/images/img_1.jpg" alt="@item.Name" class="img-fluid">
                            }
                        </figure>
                        <div class="prop-text">
                            <div class="inner">
                                <span class="price rounded">@item.Price.ToString("N0") VNĐ</span>
                                <h3 class="title">@item.Title</h3>
                                <p class="location">@item.Address</p>
                            </div>
                            <div class="prop-more-info">
                                <div class="inner d-flex">
                                    <div class="col">
                                        <span>Diện tích:</span>
                                        <strong>@item.Acreage<sup>2</sup></strong>
                                    </div>
                                    <div class="col">
                                        <span>Loại:</span>
                                        <strong>@item.RentalType.Name</strong>
                                    </div>
                                    <div class="col">
                                        <span>Đăng bởi:</span>
                                        <strong>@item.User.FullName</strong>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            }
        </div>
    </div>
</div>

Easy2GetRoom/Views/Property/Filter.cshtml
@using Easy2GetRoom.Models.PropertyViewModels
@model CatalogViewModel
@{
    ViewData["Title"] = "Lọc bài viết | Easy2GetRoom";
}
@(await Component.InvokeAsync("Slide"))
@(await Component.InvokeAsync("FilterProperty"))
<div class="site-section site-section-sm bg-light">
    <div class="container">
        <div class="row mb-5">
            <div class="col-12">
                <div class="site-section-title">
                    <h2>Kết quả lọc bài viết</h2>
                </div>
            </div>
        </div>
        <div class="row mb-5">
            @foreach (var item in Model.Data.Results)
            {
                var url = "/easy2getroom-property-p." + item.Id + ".html";
                <div class="col-md-6 col-lg-4 mb-4">
                    <a href="@url" class="prop-entry d-block">
                        <figure>
                            @if (item.PropertyImages.Count() != 0)
                            {
                                <img style="max-height:350px;
                                            width: 100%;"
                                     src="@item.PropertyImages[0].Url" alt="@item.Name" class="img-fluid">
                            }
                            else
                            {
                                <img src="~/client/images/img_1.jpg" alt="@item.Name" class="img-fluid">
                            }
                        </figure>
                        <div class="prop-text">
                            <div class="inner">
                                <span class="price rounded">@item.Price.ToString("N0") VNĐ</span>
                                <h3 class="title">@item.Title</h3>
                                <p class="location">@item.Address</p>
                            </div>
                            <div class="prop-more-info">
                                <div class="inner d-flex">
                                    <div class="col">
                                        <span>Diện tích:</span>
                                        <strong>@item.Acreage<sup>2</sup></strong>
                                    </div>
                                    <div class="col">
                                        <span>Loại:</span>
                                        <strong>@item.RentalType.Name</strong>
                                    </div>
                                    <div class="col">
                                        <span>Đăng bởi:</span>
                                        <strong>@item.User.FullName</strong>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            }
        </div>
        @(await Component.InvokeAsync("Pager", Model.Data));
    </div>
</div>

Easy2GetRoom/Views/Property/Search.cshtml
@using Easy2GetRoom.Models.PropertyViewModels
@model SearchResultViewModel

@{
    ViewData["Title"] = Model.Keyword + " | Easy2GetRoom";
}
@(await Component.InvokeAsync("Slide"))
@(await Component.InvokeAsync("FilterProperty"))
<div class="site-section site-section-sm bg-light">
    <div class="container">
        <div class="row mb-5">
            <div class="col-12">
                <div class="site-section-title">
                    <h2>Kết quả tìm kiếm cho từ khóa: @Model.Keyword</h2>
                </div>
            </div>
        </div>
        <div class="row mb-5">
            @foreach (var item in Model.Data.Results)
            {
                var url = "/easy2getroom-property-p." + item.Id + ".html";
                <div class="col-md-6 col-lg-4 mb-4">
                    <a href="@url" class="prop-entry d-block">
                        <figure>
                            <img src="~/client/images/img_1.jpg" alt="@item.Name" class="img-fluid">
                        </figure>
                        <div class="prop-text">
                            <div class="inner">
                                <span class="price rounded">@item.Price.ToString("N0") VNĐ</span>
                                <h3 class="title">@item.Title</h3>
                                <p class="location">@item.Address</p>
                            </div>
                            <div class="prop-more-info">
                                <div class="inner d-flex">
                                    <div class="col">
                                        <span>Diện tích:</span>
                                        <strong>@item.Acreage<sup>2</sup></strong>
                                    </div>
                                    <div class="col">
                                        <span>Loại:</span>
                                        <strong>@item.RentalType.Name</strong>
                                    </div>
                                    <div class="col">
                                        <span>Đăng bởi:</span>
                                        <strong>@item.User.FullName</strong>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            }
        </div>
        @(await Component.InvokeAsync("Pager", Model.Data));
    </div>
</div>